image: rocker/r-base

before_script:
    - cd /
    - wget https://www.imagemagick.org/download/ImageMagick.tar.gz
    - tar xf ImageMagick.tar.gz
    - cd ImageMagick-7*
    - ./configure
    - make
    - make install
    - ldconfig /usr/local/lib
    - magick -version
    - cd -
    - cd -

test:
   script:
    - apt-get update
    - apt-get install --yes --no-install-recommends r-cran-magick r-cran-devtools
    - R -e "devtools::install_deps()"
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual
