image: rocker/tidyverse

test:
   script:
    - add-apt-repository -y ppa:cran/imagemagick
    - apt-get update
    - apt-get install -y libmagick++-dev
    - R -e "devtools::install_deps()"
    - R -e 'devtools::check()'
