image: r-base

before_script:
    - wget https://www.imagemagick.org/download/ImageMagick.tar.gz
    - tar xf ImageMagick.tar.gz
    - cd ImageMagick-7*
    - ./configure
    - make
    - make install
    - ldconfig /usr/local/lib
    - cd -

build:
  script:
    - R -e 'install.packages("magick")'
    - R CMD build . --no-build-vignettes --no-manual
