image: r-base

test:
  before_script:
    - sudo apt-get install -y libmagick++-dev
  script:
    - R -e 'install.packages("magick")'
    - R CMD build . --no-build-vignettes --no-manual
    - R CMD check *tar.gz --no-build-vignettes --no-manual
